[package]
name = "outflux"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
thiserror = "1.0"
url = "2.2"
tracing = "0.1"
